package daintree;
/**
 * 
 * @author Karim Abulainine student id: 3314713
 * 
 *         Java for Programmers - Assignment 2
 * 
 *         Invalid Input is an Exception class for invalid inputs entered by users
 * 
 */

public class InvalidInput extends Exception {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    public InvalidInput() {
        // TODO Auto-generated constructor stub
    }
    
    public InvalidInput(String message) {
        super(message);
        // TODO Auto-generated constructor stub
    }
    
    public InvalidInput(Throwable cause) {
        super(cause);
        // TODO Auto-generated constructor stub
    }
    
    public InvalidInput(String message, Throwable cause) {
        super(message, cause);
        // TODO Auto-generated constructor stub
    }
    
    /**
     * message generated by the exception
     */
    public String getMessage()
    {
        return "Invalid Input.";
    }
    
}
