package daintree;
/**
 * 
 * @author Karim Abulainine student id: 3314713
 * 
 *         Java for Programmers - Assignment 2
 * 
 *         Invalid Input is an Exception class for invalid menu options entered by users
 * 
 */

public class InvalidMenuOption extends Exception {
    
    /**
     * 
     */
    private static final long serialVersionUID = 8202029671835965156L;
    
    public InvalidMenuOption() {
        // TODO Auto-generated constructor stub
    }
    
    public InvalidMenuOption(String arg0) {
        super(arg0);
        // TODO Auto-generated constructor stub
    }
    
    public InvalidMenuOption(Throwable arg0) {
        super(arg0);
        // TODO Auto-generated constructor stub
    }
    
    public InvalidMenuOption(String arg0, Throwable arg1) {
        super(arg0, arg1);
        // TODO Auto-generated constructor stub
    }
    
    /**
     * message generated by the exception
     */
    public String getMessage()
    {
        return "Invalid Menu Option. Please try again";
    }
    
}
